import Head from "next/head";

import styles from "../styles/Home.module.css";

import { getAuth, signInWithPopup, GoogleAuthProvider } from "firebase/auth";
import { useAuthState } from "react-firebase-hooks/auth";
import { initFirebase, database } from "../firebase/firebase-init";

import Header from "../components/Header";

//localhost:3000
export default function Home() {
  initFirebase();
  const auth = getAuth();
  const [user, loading] = useAuthState(auth);

  if (!user) {
    return (
      <div id={"contentRoot"}>
        <Head>
          <title>The Vacuous Gamer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />

        <br />

        <main className="main">
          <h1>main</h1>
        </main>

        <footer className="footer"></footer>
        {/* TODO: Find a better way to import google fonts */}
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Fullstack Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main">
        <h1>MAIN</h1>
      </main>

      <footer className="footer"></footer>
    </div>
  );
}
